### ISSUE TITLE
tidy up

### ISSUE THREAD

**Issue by yeo-yeo** [fac19/week8-TeamRocket#43]
I know it's mean to point this out when you've been working yourself to the 🦴 but don't forget to delete unnecessary empty files, console logs etc

**Comment by oliverjam** [comment]
Yeah it would also be a good idea to put all your actual app files into a folder so the repo isn't so hard to navigate. Right now you've got config files mixed up with code. It's quite common to have a `src` or `app` folder or something for the actual code part.
